language: ruby
git:
  depth: false
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
install:
  - bundle install --jobs=3 --retry=3
  - yarn
script:
  - yarn test
  - bundle exec rake
